### ISSUE TITLE
每次重启电脑都出现这个错误

### ISSUE THREAD

**Issue by mzy666888** [hyjiacan/ColorWanted#2]
操作系统: Microsoft Windows NT 6.2.9200.0
.NET版本: 4.0.30319.42000
程序版本: 2.7.2
错误消息: 调用方法时发生错误。  目标线程不再存在。
错误源:    在 System.Windows.Forms.Control.WaitForWaitHandle(WaitHandle waitHandle)
   在 System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   在 System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   在 ColorWanted.ext.FormExtension.InvokeMethod(Form form, FormInvoker invoker)
   在 ColorWanted.ext.FormExtension.<>c__DisplayClass2_0.<SlideIn>b__0()
   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   在 System.Threading.ThreadHelper.ThreadStart()

**Comment by hyjiacan** [comment]
> 操作系统: Microsoft Windows NT 6.2.9200.0
> .NET版本: 4.0.30319.42000
> 程序版本: 2.7.2
> 错误消息: 调用方法时发生错误。 目标线程不再存在。
> 错误源: 在 System.Windows.Forms.Control.WaitForWaitHandle(WaitHandle waitHandle)
> 在 System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
> 在 System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
> 在 ColorWanted.ext.FormExtension.InvokeMethod(Form form, FormInvoker invoker)
> 在 ColorWanted.ext.FormExtension.<>c__DisplayClass2_0.b__0()
> 在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
> 在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
> 在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
> 在 System.Threading.ThreadHelper.ThreadStart()

你是开启了开机自动启动吗？

**Comment by mzy666888** [comment]
是的，开机自启动

**Comment by hyjiacan** [comment]
你可以先下载当前最新版本 [2.7.7](https://github.com/hyjiacan/ColorWanted/blob/adb4a1a1edbc90a027b82800ce10bdd71e309a8e/ColorWanted/bin/Release/ColorWanted.exe)试试

我的电脑是windows10，未出现这个问题
