### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by mzy666888** [hyjiacan/ColorWanted#3]
操作系统: Microsoft Windows NT 6.2.9200.0
.NET版本: 4.0.30319.42000
程序版本: 3.0.5
错误消息: 调用方法时发生错误。  目标线程不再存在。
错误源:    在 System.Windows.Forms.Control.WaitForWaitHandle(WaitHandle waitHandle)
   在 System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   在 System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   在 ColorWanted.ext.FormExtension.InvokeMethod(Form form, FormInvoker invoker)
   在 System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)
   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   在 System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by hyjiacan** [comment]
多谢反馈
