### ISSUE TITLE
报了个错

### ISSUE THREAD

**Issue by ghost** [hyjiacan/ColorWanted#4]
操作系统: Microsoft Windows NT 6.2.9200.0
.NET版本: 4.0.30319.42000
程序版本: 3.3.0
错误消息: 调用方法时发生错误。  目标线程不再存在。
错误源:    在 System.Windows.Forms.Control.WaitForWaitHandle(WaitHandle waitHandle)
   在 System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   在 System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   在 ColorWanted.ext.FormExtension.InvokeMethod(Form form, FormInvoker invoker)
   在 ColorWanted.ext.FormExtension.<>c__DisplayClass2_0.<SlideIn>b__0()
   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   在 System.Threading.ThreadHelper.ThreadStart()

**Comment by hyjiacan** [comment]
此问题已在早期版本解决，请看 #3 

更新至最新版本即可

**Comment by ghost** [comment]
> 此问题已在早期版本解决，请看[＃3](https://github.com/hyjiacan/ColorWanted/issues/3)
> 
> 更新至最新版本即可

最新版不是3.3.0？
