### ISSUE TITLE
高分屏显示有问题

### ISSUE THREAD

**Issue by niices** [hyjiacan/ColorWanted#5]
颜色显示重叠了，然后设置项字体很小
![image](https://user-images.githubusercontent.com/8327775/87250130-9825b280-c495-11ea-9854-466a7a701fab.png)
![image](https://user-images.githubusercontent.com/8327775/87250141-a5db3800-c495-11ea-8022-b3ae8a705ddb.png)

**Comment by niices** [comment]
设备是联想小新 13 Pro 2020
分辨率是2560*1660

**Comment by hyjiacan** [comment]
多谢反馈。此问题已经确认，由于技术有限，目前暂未解决其核心问题。

**Comment by hyjiacan** [comment]
问题已经在版本 [4.0.1](https://gitee.com/hyjiacan/ColorWanted/attach_files) 修复
