### ISSUE TITLE
不好意思，出问题了

### ISSUE THREAD

**Issue by dogzhang** [hyjiacan/ColorWanted#7]
操作系统: Microsoft Windows NT 6.2.9200.0
.NET版本: 4.0.30319.42000
程序版本: 4.0.1
错误消息: 调用方法时发生错误。  目标线程不再存在。
错误源:    在 System.Windows.Forms.Control.WaitForWaitHandle(WaitHandle waitHandle)
   在 System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   在 System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   在 ColorWanted.ext.FormExtension.InvokeMethod(Form form, FormInvoker invoker)
   在 ColorWanted.ext.FormExtension.<>c__DisplayClass2_0.<SlideIn>b__0()
   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   在 System.Threading.ThreadHelper.ThreadStart()

**Comment by hyjiacan** [comment]
这个问题已经解决了，只是最近忙一直没有发新包

**Comment by hyjiacan** [comment]
问题已经解决，请更新版本至 [4.10.1](https://github.com/hyjiacan/ColorWanted/releases/tag/4.10.1)
